permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "whsellu"
email: "wshell84@gmail.com"
description: "C Developer"
github_username:  "wshellu"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "rainyalley"



#url: "http://blog.rainyalley.com"
#imgrepo: "http://blog.rainyalley.com/static/img"


url: "http://wshellu.github.io"
imgrepo: "http://wshellu.github.io/static/img"
gems: [jekyll-paginate]

